name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - deploy/production

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run SonarQube Analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          docker run \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli:5.0.1 \
            -Dsonar.projectKey=my_project_key \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  security-scan:
    needs: static-code-analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Update dependencies and run Snyk security scan
        run: |
          echo "Updating dependencies..."
          npm install -g npm-check-updates
          ncu -u
          npm install
          npm audit fix
          echo "Running Snyk security scan..."
          npx snyk auth ${{ secrets.SNYK_TOKEN }}
          npx snyk test --all-projects

  tests:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Code Coverage
        run: npm run test:coverage

  build_and_deliver:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker and Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create and use local Buildx builder
        run: |
          docker buildx create --use --name my-local-builder
          docker buildx inspect --bootstrap

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image using Buildx
        run: |
          docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/todo-frontend:stable --build-arg VUE_APP_API_URL=${{ secrets.BACKEND_EC2_IP }} -f Dockerfile . --load --push
      - name: List Docker images for verification
        run: docker images

  deploy:
    needs: build_and_deliver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to EC2 Frontend Instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          FRONTEND_EC2_IP: ${{ secrets.FRONTEND_EC2_IP }}
          BACKEND_EC2_IP: ${{ secrets.BACKEND_EC2_IP }}
        run: |
          echo "${{ env.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.FRONTEND_EC2_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.BACKEND_EC2_IP }}" > backend_ec2_ip.txt
          scp -i private_key.pem docker-compose.yml backend_ec2_ip.txt ubuntu@${{ env.FRONTEND_EC2_IP }}:/home/ubuntu/
          ssh -i private_key.pem ubuntu@${{ env.FRONTEND_EC2_IP }} 'export BACKEND_EC2_IP=$(cat /home/ubuntu/backend_ec2_ip.txt) && docker-compose -f /home/ubuntu/docker-compose.yml pull && docker-compose -f /home/ubuntu/docker-compose.yml up -d'
          